<!ENTITY spanButton "&lt;span class=&quot;btn&quot;&gt;Button&lt;/span&gt;">
<!ENTITY sup2 "&#178;">

<!ELEMENT real-estate (agencies, owners, properties, flats)>
<!ATTLIST real-estate language (EN) #FIXED "EN">

<!ELEMENT agencies (agency*)>
<!ELEMENT agency (name, address | email | phone)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

<!ELEMENT owners (owner*)>
<!ELEMENT owner (name, address)>
<!ATTLIST owner oid ID #REQUIRED>

<!ELEMENT properties (property*)>
<!ELEMENT property (name, address, description, number-of-flats, features?)>
<!ATTLIST property pid ID #REQUIRED>
<!ATTLIST property owner-ref IDREF #IMPLIED>

<!ELEMENT address (street-number, state, country?, postal-code)>
<!ELEMENT street-number (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postal-code (#PCDATA)>

<!ELEMENT description ANY>

<!ELEMENT number-of-flats (#PCDATA)>

<!ELEMENT features (feature, feature, feature?, feature?, feature?)>
<!ELEMENT feature (#PCDATA)>

<!ELEMENT flats (flat, flat, flat*)>
<!ELEMENT flat (name, address, description, features?, records?)>
<!ATTLIST flat fid ID #REQUIRED>
<!ATTLIST flat property-ref IDREF #IMPLIED>
<!ATTLIST flat comfort (A|B|C|D|E|F) "F">

<!ELEMENT records (record+)>
<!ELEMENT record (date, info | records)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT info (#PCDATA)>
