<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="daw">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="modulo" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="codigo" type="xs:string"/>
                            <xs:element name="profesor" type="xs:string"/>
                            <xs:element name="fechas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="inicio" type="fechaTipo"/>
                                        <xs:element name="fin" type="fechaTipo"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="fechaTipo">
        <xs:sequence>
            <xs:element name="dia" type="xs:positiveInteger"/>
            <xs:element name="mes" type="xs:positiveInteger"/>
            <xs:element name="anio" type="xs:gYear"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>
