<!ENTITY % MODE "STANDARD">

<!ENTITY % OWNER_VERBOSE "
    <!ELEMENT owner (name, address, description)>
">

<!ENTITY % OWNER_STANDARD "
    <!ELEMENT owner (name, address)>
">

<![ %MODE = "VERBOSE" [
    %OWNER_VERBOSE;
]]>

<![ %MODE = "STANDARD" [
    %OWNER_STANDARD;
]]>

<!ELEMENT real-estate (agencies, owners, properties, flats)>
<!ATTLIST real-estate language (EN) #FIXED "EN">

<!ELEMENT agencies (agency*)>
<!ELEMENT agency (name, address | email | phone)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

<!ELEMENT owners (owner*)>

<!ELEMENT address (street-number, state, country?, postal-code)>
<!ELEMENT street-number (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT postal-code (#PCDATA)>

<!ELEMENT description ANY>

<!ELEMENT properties (property*)>
<!ELEMENT property (name, address, description, number-of-flats, features?)>
<!ATTLIST property pid ID #REQUIRED>
<!ATTLIST property owner-ref IDREF #IMPLIED>

<!ELEMENT number-of-flats (#PCDATA)>

<!ELEMENT features (feature, feature, feature?, feature?, feature?)>
<!ELEMENT feature (#PCDATA)>

<!ELEMENT flats (flat, flat, flat*)>
<!ELEMENT flat (name, address, description, features?, records?)>
<!ATTLIST flat fid ID #REQUIRED>
<!ATTLIST flat property-ref IDREF #IMPLIED>
<!ATTLIST flat comfort (A|B|C|D|E|F) "F">

<!ELEMENT records (record+)>
<!ELEMENT record (date, info | records)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT info (#PCDATA)>
